In [4]:
pip install numpy # 安裝numpy

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#'


In [5]:
import numpy as np

In [6]:
np.zeros(3)   # 可以產出一個0的陣列

array([0., 0., 0.])

In [7]:
type(np.zeros(3)) #型別為陣列

numpy.ndarray

In [8]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.zeros((2, 3), dtype=int) #原為浮點數，改為整數

array([[0, 0, 0],
       [0, 0, 0]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones(5, dtype=int)

array([1, 1, 1, 1, 1])

In [12]:
np.empty((3, 3)) # 提供無意義數值

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.16196447e-321],
       [1.78019082e-306, 0.00000000e+000, 0.00000000e+000]])

In [13]:
np.full(3, 255) # 產生特定陣列

array([255, 255, 255])

In [14]:
np.random.rand(2, 5) # 產生2*5，內有0~1的亂數

array([[0.80426624, 0.47082268, 0.84955729, 0.81438007, 0.08097626],
       [0.53678281, 0.54488041, 0.97234938, 0.7124981 , 0.95858805]])

In [15]:
np.random.randint(low=2, high=8, size = (2, 3), dtype = int)

array([[7, 2, 6],
       [4, 4, 2]])

In [16]:
test_arr = np.array([2, 4, 4]) #產出一陣列
test_arr

array([2, 4, 4])

In [17]:
test_arr.ndim

1

In [18]:
test_arr.shape

(3,)

In [19]:
test_arr.size # 計算有幾個數值

3

In [20]:
np.random.randint(low=2, high=8, size=(2,3), dtype=int).shape

(2, 3)

In [21]:
np.random.randint(low=2, high=8, size=(2,3), dtype=int).size

6

In [22]:
arr = np.random.randint(low=2, high=8, size=(2,3), dtype=int)
arr

array([[7, 4, 2],
       [3, 4, 3]])

In [23]:
arr.reshape((3,2))

array([[7, 4],
       [2, 3],
       [4, 3]])

In [24]:
arr.reshape((3, -1)) # 不想算長度時，可以直接輸入-1

array([[7, 4],
       [2, 3],
       [4, 3]])

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [26]:
arr.mean() # 平均

3.5

In [27]:
np.mean(arr) # 平均

3.5

In [28]:
arr.max() # 最大值

6

In [29]:
arr.min() # 最小值

1

In [30]:
np.median(arr) # 中位數

3.5

In [34]:
np.percentile(arr, 50)

3.5

In [35]:
np.percentile(arr, 50, interpolation='higher')

C:\Users\Tibame_EX14\AppData\Local\Temp\ipykernel_31828\3951993827.py:1: DeprecationWarning: the `interpolation=` argument to percentile was renamed to `method=`, which has additional options.
Users of the modes 'nearest', 'lower', 'higher', or 'midpoint' are encouraged to review the method they used. (Deprecated NumPy 1.22)
  np.percentile(arr, 50, interpolation='higher')


4

In [36]:
arr

array([1, 2, 3, 4, 5, 6])

In [37]:
arr * 2

array([ 2,  4,  6,  8, 10, 12])

In [38]:
arr + 10

array([11, 12, 13, 14, 15, 16])

# 標準差

In [39]:
mu = arr.mean()

In [40]:
arr - mu

array([-2.5, -1.5, -0.5,  0.5,  1.5,  2.5])

In [41]:
arr.sum()

21

In [42]:
(arr - mu).mean()

0.0

In [43]:
np.power((arr - mu), 2)   #次方

array([6.25, 2.25, 0.25, 0.25, 2.25, 6.25])

In [44]:
np.power((arr - mu), 2).mean()

2.9166666666666665

In [45]:
np.sqrt(
    np.power(
        (arr - mu), 2
    ).mean()
)

1.707825127659933

In [46]:
arr.std() #標準差

1.707825127659933

In [47]:
np.random.normal(0, 1, 10)

array([-0.34509072,  1.05863915,  0.71314621, -0.87206084, -0.84286018,
       -0.11244183,  0.70792922, -0.3511382 ,  1.43954373,  0.34863101])

# 運算子

In [48]:
arr

array([1, 2, 3, 4, 5, 6])

In [49]:
arr > 3

array([False, False, False,  True,  True,  True])

In [50]:
~(arr > 3)

array([ True,  True,  True, False, False, False])

In [51]:
arr > 2 

array([False, False,  True,  True,  True,  True])

In [52]:
arr < 5

array([ True,  True,  True,  True, False, False])

In [53]:
(arr > 2) & (arr < 5) # 交集

array([False, False,  True,  True, False, False])

In [54]:
set([3, 4, 5, 6])

{3, 4, 5, 6}

In [55]:
set([1, 2, 3, 4])

{1, 2, 3, 4}

In [56]:
set([3, 4, 5, 6]) & set([1, 2, 3, 4]) # 交集

{3, 4}

In [57]:
set([3, 4, 5, 6]) | set([1, 2, 3, 4]) # 聯集

{1, 2, 3, 4, 5, 6}

In [58]:
set([3, 4, 5, 6]) - set([1, 2, 3, 4]) # 差集

{5, 6}

In [59]:
(arr > 2) | (arr < 5) #聯集

array([ True,  True,  True,  True,  True,  True])

In [60]:
(arr > 2) ^ (arr < 5) #補集

array([ True,  True, False, False,  True,  True])

In [61]:
(arr >2) & (arr <5)

array([False, False,  True,  True, False, False])

In [62]:
~(arr >2) & ~(arr <5)

array([False, False, False, False, False, False])